learning_users/basic_app/urls.py
from django.urls import path
from .views import basic_app_index, register, user_logout, special, user_login

app_name = 'basic_app'

urlpatterns = [
    path('', basic_app_index, name='basic_app_index'),
    path('register/', register, name='register'),
    path('logout/', user_logout, name='logout'),
    path('special/', special, name='special'),
    path('user_login/', user_login, name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app.views import basic_app_index

urlpatterns = [
    path('', basic_app_index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse  # django.core.urlresolvers
from django.contrib.auth.decorators import login_required


def basic_app_index(request):
    return render(request, 'basic_app/basic_app_index.html')


@login_required()
def special(request):
    return HttpResponse("You are logged in, Nice!")


@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                  {
                      'user_form': user_form,
                      'profile_form': profile_form,
                      'registered': registered
                  })


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print(f"Username: {username} and password {password}")
            return HttpResponse("Invalid login details suplied!")
    else:
        return render(request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-collapse">
            <a class="navbar-brand" href="{% url 'basic_app:basic_app_index' %}">DJANGO</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a> </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:register' %}">Register</a> </li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:logout' %}">Logout</a> </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
<div class="container">
    {% block body_block %}
<!--    Anything outside of this will be inherited if you extend-->
    {% endblock%}
</div>

</body>
</html>

learning_users/templates/basic_app/basic_app_index.html
{% extends "basic_app/base.html" %}
    <h1>BASIC APP INDEX</h1>
{% block body_block %}
    <div class="jumbotron">
        <h1>Django Level Five</h1>
    </div>
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Please Log In!</h1>
        <form action="{% url 'basic_app:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="usernmae">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">
            <br/>
            <label for="password">Password:</label>
            <input type="text" name="password">
            <br/>
            <input type="submit" name="" value="Login">
        </form>

    </div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}
    <div class="container">
        <div class="jumbotron">
            {% if registered %}
                <h1> Thank you for registering!</h1>
            {% else %}
                <h1>Register Here!</h1>
                <h3>Fill out the form:</h3>

                <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <input type="submit" name="" value="Register">
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

learning_users/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ROOT PROJECT INDEX</title>
</head>
<body>
    <h1>ROOT PROJECT INDEX</h1>
</body>
</html>